version: '2'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      MY_SQL_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql

  springboot:
     image: farahbgdh/projetdevopsimage
     container_name: devopsprojectfinal
     restart: on-failure
     ports:
      - 8089:8089
     depends_on:
      - mysqldb
  angular:
    container_name: dockercomposeangular
    image: dockercomposeangular
    restart: on-failure
    ports:
     - 4200:4200